apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoind-claim0
spec:
  storageClassName: btc-longhorn-noreplicas
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
