apiVersion: v1
kind: Service
metadata:
  name: bitcoind
spec:
  ports:
  - name: "18443"
    port: 18443
    targetPort: 18443
  - name: "8333"
    port: 8333
    targetPort: 8333
  selector:
    io.kompose.service: bitcoind
status:
  loadBalancer: {}
