apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bitcoind
  name: bitcoind
spec:
  containers:
  - image: lncm/bitcoind:v23.0
    name: bitcoind
    ports:
    - containerPort: 18443
    - containerPort: 8333
    resources: {}
    volumeMounts:
    - mountPath: /data
      name: bitcoind-vol0
  - image: getumbrel/btc-rpc-explorer:v3.3.0
    name: btc-rpc-explorer
    ports:
    - containerPort: 3002
    env:
    - name: BTCEXP_BITCOIND_HOST
      value: bitcoind
    - name: BTCEXP_BITCOIND_PORT
      value: "8333"
    - name: BTCEXP_BASEURL
      value: "/btc-explorer/"
    - name: BTCEXP_PORT
      value: "3002"
  restartPolicy: OnFailure
  volumes:
  - name: bitcoind-vol0
    persistentVolumeClaim:
      claimName: bitcoind-claim0
status: {}
